package rpg.core;

import java.util.Arrays;

import com.google.common.eventbus.EventBus;

import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.ModMetadata;

public class MinePGModContainer extends DummyModContainer {

	public MinePGModContainer() {
		super(new ModMetadata());

		ModMetadata meta = getMetadata();
		meta.autogenerated = false;
		meta.authorList = Arrays.asList("ModderPenguin");
		meta.name = CoreReference.NAME;
		meta.modId = CoreReference.MOD_ID;
		meta.description = "This Mod is Work in Progress.";
		meta.version = CoreReference.VERSION;
	}

	@Override
	public boolean registerBus(EventBus bus, LoadController controller) {
		return true;
	}
}